"""LLM Response Parser for Horizon Trading Platform.

Parses Claude API responses and converts them into TradeProposal objects.
Handles JSON extraction, schema validation, field validation and normalization.
"""

import json
import logging
import re
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from decimal import Decimal, InvalidOperation
from typing import Optional

logger = logging.getLogger(__name__)


class LLMParseError(Exception):
    """Raised when the LLM response cannot be parsed or has fatal structural errors."""

    pass


VALID_EXCHANGES = ("binance", "htx", "hyperliquid", "bitget")
VALID_SIDES = ("buy", "sell")
VALID_ORDER_TYPES = ("market", "limit")
VALID_RISK_TIERS = ("low", "medium", "high")
DEFAULT_PRICE_DRIFT_THRESHOLD_PCT = 3.0
DEFAULT_RISK_TIER = "medium"
DEFAULT_EXPIRES_HOURS = 24


@dataclass
class TradeProposal:
    """Trade proposal generated by LLM analysis.

    Matches the proposals table schema in the database.
    """

    id: str
    status: str
    exchange: str
    symbol: str
    side: str
    order_type: str
    price: Optional[float]
    volume: float
    confidence_score: int
    risk_tier: str
    llm_rationale: str
    llm_raw_response: str
    technical_context: str
    market_snapshot: str
    portfolio_snapshot: Optional[str]
    guardrail_result: Optional[str]
    approved_by: Optional[str]
    approved_at: Optional[datetime]
    executed_order_id: Optional[str]
    expires_at: datetime
    price_drift_threshold_pct: float
    proposed_price: float
    created_at: datetime
    action_type: str = "open"  # one of: open, close, reduce

    @property
    def is_expired(self) -> bool:
        """Check if the proposal has expired."""
        return datetime.now(timezone.utc) > self.expires_at

    @property
    def is_long(self) -> bool:
        """Check if this is a long position (buy side)."""
        return self.side == "buy"

    @property
    def is_short(self) -> bool:
        """Check if this is a short position (sell side)."""
        return self.side == "sell"

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return {
            "id": self.id,
            "status": self.status,
            "exchange": self.exchange,
            "symbol": self.symbol,
            "side": self.side,
            "order_type": self.order_type,
            "price": self.price,
            "volume": self.volume,
            "confidence_score": self.confidence_score,
            "risk_tier": self.risk_tier,
            "action_type": self.action_type,
            "llm_rationale": self.llm_rationale,
            "llm_raw_response": self.llm_raw_response,
            "technical_context": self.technical_context,
            "market_snapshot": self.market_snapshot,
            "portfolio_snapshot": self.portfolio_snapshot,
            "guardrail_result": self.guardrail_result,
            "approved_by": self.approved_by,
            "approved_at": self.approved_at.isoformat() if self.approved_at else None,
            "executed_order_id": self.executed_order_id,
            "expires_at": self.expires_at.isoformat(),
            "price_drift_threshold_pct": self.price_drift_threshold_pct,
            "proposed_price": self.proposed_price,
            "created_at": self.created_at.isoformat(),
        }


class LLMResponseParser:
    """Parses LLM responses and converts them to TradeProposal objects."""

    def __init__(self, asset_whitelist: list[str] | None = None) -> None:
        """Initialize the parser.

        Args:
            asset_whitelist: List of allowed trading pair symbols.
        """
        self._asset_whitelist = asset_whitelist or []

    def _extract_json(self, text: str) -> dict:
        """Extract JSON object from text.

        Attempts regex extraction of JSON from markdown code blocks first,
        then falls back to finding the first {...} block.

        Args:
            text: Raw response text.

        Returns:
            Parsed JSON dict.

        Raises:
            LLMParseError: If no valid JSON found.
        """
        # Try markdown code block first
        code_block_pattern = r"```json\s*(.*?)\s*```"
        match = re.search(code_block_pattern, text, re.DOTALL)
        if match:
            json_str = match.group(1)
            try:
                return json.loads(json_str)
            except json.JSONDecodeError as e:
                raise LLMParseError(f"Invalid JSON in code block: {e}")

        # Try finding any {...} block
        brace_pattern = r"\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}"
        match = re.search(brace_pattern, text, re.DOTALL)
        if match:
            json_str = match.group(0)
            try:
                return json.loads(json_str)
            except json.JSONDecodeError as e:
                raise LLMParseError(f"Invalid JSON in braces: {e}")

        # Try parsing entire text as JSON
        try:
            return json.loads(text)
        except json.JSONDecodeError as e:
            raise LLMParseError(f"No valid JSON found in response: {e}")

    def parse(
        self,
        raw_response: str,
        market_snapshot: dict,
        portfolio_snapshot: dict,
        technical_context: dict,
    ) -> list[TradeProposal]:
        """Parse LLM response and convert to TradeProposal objects.

        Args:
            raw_response: Raw response string from LLM API.
            market_snapshot: Current market data snapshot.
            portfolio_snapshot: Current portfolio state.
            technical_context: Technical indicators and analysis context.

        Returns:
            List of valid TradeProposal objects. May be empty.

        Raises:
            LLMParseError: If the response has fatal structural errors.
        """
        # Step 1: Extract JSON
        try:
            parsed = self._extract_json(raw_response)
        except LLMParseError:
            raise

        # Step 2: Validate schema
        if not isinstance(parsed, dict):
            raise LLMParseError("Response must be a JSON object")

        required_keys = ("analysis_summary", "confidence_explanation", "proposals")
        for key in required_keys:
            if key not in parsed:
                raise LLMParseError(f"Missing key: {key}")

        if not isinstance(parsed["proposals"], list):
            raise LLMParseError("proposals must be a list")

        proposals = []

        # Step 3: Parse proposals
        for i, proposal in enumerate(parsed["proposals"]):
            try:
                trade_proposal = self._parse_single_proposal(
                    proposal, market_snapshot, portfolio_snapshot, technical_context, raw_response
                )
                if trade_proposal is not None:
                    proposals.append(trade_proposal)
            except Exception as e:
                logger.warning(f"Failed to parse proposal {i}: {e}")
                continue

        return proposals

    def _parse_single_proposal(
        self,
        proposal: dict,
        market_snapshot: dict,
        portfolio_snapshot: dict,
        technical_context: dict,
        raw_response: str,
    ) -> Optional[TradeProposal]:
        """Parse a single proposal dict into a TradeProposal.

        Args:
            proposal: Single proposal dict from LLM response.
            market_snapshot: Current market data snapshot.
            portfolio_snapshot: Current portfolio state.
            technical_context: Technical indicators context.
            raw_response: Original raw response.

        Returns:
            TradeProposal or None if validation fails.
        """
        # Validate required fields
        required_fields = [
            "exchange",
            "symbol",
            "side",
            "order_type",
            "volume",
            "confidence_score",
            "risk_tier",
            "rationale",
        ]
        missing_fields = [f for f in required_fields if f not in proposal]
        if missing_fields:
            logger.warning(f"Skipping proposal, missing fields: {missing_fields}")
            return None

        # Validate exchange
        exchange = proposal["exchange"]
        if exchange not in VALID_EXCHANGES:
            logger.warning(f"Skipping proposal, invalid exchange: {exchange}")
            return None

        # Validate side
        side = proposal["side"]
        if side not in VALID_SIDES:
            logger.warning(f"Skipping proposal, invalid side: {side}")
            return None

        # Validate order_type
        order_type = proposal["order_type"]
        if order_type not in VALID_ORDER_TYPES:
            logger.warning(f"Skipping proposal, invalid order_type: {order_type}")
            return None

        # Validate symbol against whitelist
        symbol = proposal["symbol"]
        if self._asset_whitelist and symbol not in self._asset_whitelist:
            logger.warning(f"Skipping proposal, symbol {symbol} not in whitelist")
            return None

        # Validate and clamp confidence_score
        confidence_score = proposal["confidence_score"]
        if not isinstance(confidence_score, int):
            try:
                confidence_score = int(confidence_score)
            except (ValueError, TypeError):
                logger.warning(
                    f"Invalid confidence_score {confidence_score}, clamping to valid range"
                )
                confidence_score = 0

        if confidence_score < 0:
            logger.warning(
                f"confidence_score {confidence_score} below 0, clamping to 0"
            )
            confidence_score = 0
        elif confidence_score > 100:
            logger.warning(
                f"confidence_score {confidence_score} above 100, clamping to 100"
            )
            confidence_score = 100

        # Validate and default risk_tier
        risk_tier = proposal["risk_tier"]
        if risk_tier not in VALID_RISK_TIERS:
            logger.warning(
                f"Invalid risk_tier {risk_tier}, defaulting to {DEFAULT_RISK_TIER}"
            )
            risk_tier = DEFAULT_RISK_TIER

        # Validate action_type
        raw_action = proposal.get("action_type", "open")
        action_type = raw_action if raw_action in ("open", "close", "reduce") else "open"

        # Validate price for limit orders
        price = proposal.get("price")
        if order_type == "limit":
            if price is None:
                logger.warning("Skipping proposal, limit order without price")
                return None
            try:
                price = float(price)
            except (ValueError, TypeError):
                logger.warning(f"Invalid price {price} for limit order")
                return None

        # Parse volume as Decimal
        volume = proposal["volume"]
        try:
            volume_decimal = Decimal(str(volume))
            volume = float(volume_decimal)
        except InvalidOperation:
            logger.warning(f"Invalid volume {volume}")
            return None

        # Get current market price for the symbol
        proposed_price = self._get_market_price(symbol, market_snapshot)
        if proposed_price is None:
            logger.warning(f"No market price found for symbol {symbol}")
            return None

        # Generate proposal_id as UUID v4
        proposal_id = str(uuid.uuid4())

        # Set status and expiration
        status = "proposed"
        expires_at = datetime.now(timezone.utc) + timedelta(hours=DEFAULT_EXPIRES_HOURS)
        created_at = datetime.now(timezone.utc)

        # JSON-serialize context dicts
        market_snapshot_json = json.dumps(market_snapshot)
        portfolio_snapshot_json = json.dumps(portfolio_snapshot)
        technical_context_json = json.dumps(technical_context)

        return TradeProposal(
            id=proposal_id,
            status=status,
            exchange=exchange,
            symbol=symbol,
            side=side,
            order_type=order_type,
            price=price,
            volume=volume,
            confidence_score=confidence_score,
            risk_tier=risk_tier,
            action_type=action_type,
            llm_rationale=proposal["rationale"],
            llm_raw_response=raw_response,
            technical_context=technical_context_json,
            market_snapshot=market_snapshot_json,
            portfolio_snapshot=portfolio_snapshot_json,
            guardrail_result=None,
            approved_by=None,
            approved_at=None,
            executed_order_id=None,
            expires_at=expires_at,
            price_drift_threshold_pct=DEFAULT_PRICE_DRIFT_THRESHOLD_PCT,
            proposed_price=proposed_price,
            created_at=created_at,
        )

    def _get_market_price(self, symbol: str, market_snapshot: dict) -> Optional[float]:
        """Get current market price for a symbol from market snapshot.

        Args:
            symbol: Trading pair symbol.
            market_snapshot: Market data snapshot dict.

        Returns:
            Current price or None if not found.
        """
        # market_snapshot structure may vary, try common formats
        # Format1: {symbol: {exchange: {price: value}}}
        if symbol in market_snapshot:
            data = market_snapshot[symbol]
            if isinstance(data, dict):
                # Try to get price from first exchange or calculate from bid/ask
                if "last_price" in data:
                    return float(data["last_price"])
                elif "price" in data:
                    return float(data["price"])
                # Try nested exchange format
                for exchange_data in data.values():
                    if isinstance(exchange_data, dict):
                        if "last_price" in exchange_data:
                            return float(exchange_data["last_price"])
                        elif "price" in exchange_data:
                            return float(exchange_data["price"])

        # Format 2: {exchange: {symbol: {price: value}}}
        for exchange_data in market_snapshot.values():
            if isinstance(exchange_data, dict) and symbol in exchange_data:
                symbol_data = exchange_data[symbol]
                if isinstance(symbol_data, dict):
                    if "last_price" in symbol_data:
                        return float(symbol_data["last_price"])
                    elif "price" in symbol_data:
                        return float(symbol_data["price"])

        # Format 3: {tickers: {symbol: {price: value}}}
        if "tickers" in market_snapshot:
            tickers = market_snapshot["tickers"]
            if symbol in tickers:
                ticker = tickers[symbol]
                if isinstance(ticker, dict):
                    if "last_price" in ticker:
                        return float(ticker["last_price"])
                    elif "price" in ticker:
                        return float(ticker["price"])

        # Format 4: direct price value
        if "price" in market_snapshot:
            return float(market_snapshot["price"])

        # Format 5: tickers as a list of dicts [{symbol, price/last_price, ...}, ...]
        if "tickers" in market_snapshot and isinstance(market_snapshot["tickers"], list):
            for t in market_snapshot["tickers"]:
                if isinstance(t, dict) and t.get("symbol") == symbol:
                    if "last_price" in t:
                        return float(t["last_price"])
                    if "price" in t:
                        return float(t["price"])

        return None