-- Migration 002: Proposals, Strategy Configs, and LLM History
-- Adds tables for LLM-driven trade proposals and strategy configuration

-- Table: proposals - stores trade proposals generated by LLM analysis
CREATE TABLE IF NOT EXISTS proposals (
    id TEXT PRIMARY KEY,
    status TEXT NOT NULL CHECK(status IN ('proposed','approved','rejected','expired','executed','auto_executed')),
    exchange TEXT NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    order_type TEXT NOT NULL,
    price REAL,
    volume REAL NOT NULL,
    confidence_score INTEGER NOT NULL CHECK(confidence_score BETWEEN 0 AND 100),
    risk_tier TEXT NOT NULL CHECK(risk_tier IN ('low','medium','high')),
    llm_rationale TEXT NOT NULL,
    llm_raw_response TEXT,
    technical_context TEXT,
    market_snapshot TEXT NOT NULL,
    portfolio_snapshot TEXT,
    guardrail_result TEXT,
    approved_by TEXT,
    approved_at TIMESTAMP,
    executed_order_id TEXT,
    expires_at TIMESTAMP NOT NULL,
    price_drift_threshold_pct REAL NOT NULL DEFAULT 3.0,
    proposed_price REAL NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (exchange) REFERENCES exchanges(name),
    FOREIGN KEY (executed_order_id) REFERENCES orders(id)
);

-- Table: strategy_configs - configuration for different trading strategies
CREATE TABLE IF NOT EXISTS strategy_configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    enabled INTEGER NOT NULL DEFAULT 1,
    mode TEXT NOT NULL CHECK(mode IN ('paper','live')) DEFAULT 'live',
    autonomy_enabled INTEGER NOT NULL DEFAULT 0,
    min_confidence_threshold INTEGER DEFAULT 75,
    max_risk_tier TEXT DEFAULT 'low',
    analysis_interval_hours INTEGER DEFAULT 8,
    asset_whitelist TEXT NOT NULL,
    max_position_pct REAL DEFAULT 20.0,
    max_daily_loss_pct REAL DEFAULT 5.0,
    max_exchange_exposure_pct REAL DEFAULT 50.0,
    cooldown_seconds INTEGER DEFAULT 300,
    order_min_notional REAL DEFAULT 10.0,
    order_max_notional REAL DEFAULT 10000.0,
    price_drift_expiry_pct REAL DEFAULT 3.0,
    system_prompt TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: llm_analysis_history - audit log of all LLM API calls
CREATE TABLE IF NOT EXISTS llm_analysis_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_config_id INTEGER NOT NULL,
    triggered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completion_status TEXT NOT NULL CHECK(completion_status IN ('success','error','timeout')),
    latency_ms INTEGER,
    token_count_input INTEGER,
    token_count_output INTEGER,
    raw_prompt TEXT NOT NULL,
    raw_response TEXT,
    parsed_proposals_count INTEGER DEFAULT 0,
    error_message TEXT,
    FOREIGN KEY (strategy_config_id) REFERENCES strategy_configs(id)
);

-- Table: technical_indicators - cached technical indicator values
CREATE TABLE IF NOT EXISTS technical_indicators (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    rsi_14 REAL,
    macd_line REAL,
    macd_signal REAL,
    macd_histogram REAL,
    ema_20 REAL,
    ema_50 REAL,
    bollinger_upper REAL,
    bollinger_lower REAL,
    atr_14 REAL,
    computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(symbol, computed_at)
);

-- Seed data: Default long-term strategy configuration
INSERT INTO strategy_configs (
    name,
    enabled,
    mode,
    autonomy_enabled,
    min_confidence_threshold,
    max_risk_tier,
    analysis_interval_hours,
    asset_whitelist,
    system_prompt
) VALUES (
    'default_long_term',
    1,
    'live',
    0,
    75,
    'low',
    8,
    '["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT"]',
    'You are a quantitative trading analyst for the Horizon Trading Platform. Your role is to perform long-term technical and fundamental analysis to recommend optimal trade entries and exits.

## Response Format
You must respond with a strict JSON object containing a "proposals" array. Each proposal in the array must have the following fields:
- "symbol": Trading pair symbol (e.g., "BTCUSDT")
- "side": Either "buy" or "sell"
- "order_type": Either "market" or "limit"
- "price": Entry price (required for limit orders, optional for market orders)
- "volume": Position size in base currency
- "confidence_score": Integer from 0-100 indicating conviction level
- "risk_tier": One of "low", "medium", or "high"
- "rationale": Detailed explanation of why this trade is recommended

## Analysis Framework
1. Perform technical analysis using provided indicators (RSI, MACD, EMA, Bollinger Bands, ATR)
2. Consider current market conditions and trends
3. Evaluate portfolio state and allocation
4. Assess risk-reward ratio for each potential trade
5. Only propose trades with confidence_score >= 75 and risk_tier of "low" or "medium"

## Constraints
- Only analyze assets in the whitelist: BTCUSDT, ETHUSDT, SOLUSDT, BNBUSDT
- Maximum position size is 20% of portfolio
- Maximum daily loss tolerance is 5%
- Return an empty proposals array if no trade meets the criteria'
);